version: "3.8"

services:
  db:
    env_file:
      - .env
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local